### PR TITLE
Feature - Proper immutable support via builders

### LINKED ISSUE #4: Incoming is not well suited for "immutable" objects
Hi,

I think that the interfaces should be changed to allow constructing objects only by calling its constructors, without the need of using setter methods.

In the exposed examples (README) we can see that the object is constructed before being filled, this imposes several restrictions on the software architecture, because it makes impossible to combine this library with immutable objects.

### PR DESCRIPTION
**Pull request by Rican7**
This PR implements a much requested feature, and closes #4, by supporting immutable values/models much better via the new "builders" and type-definition processing.

Incoming was designed to take loose input, transform it (potentially sanitize it), and then populate value objects and data-structures with that input. Unfortunately, the design never really took immutable objects or un-instantiated objects into account. While [there are definitely ways to work around the shortcomings of the design][issue-4-workaround], no solution was quite ideal.

Well, this PR solves this issue by **introducing a new "builder" concept**, designed to use **alongside** "hydrators". New interfaces, abstractions, and processes were introduced to make it so that building values, whether immutable or not, could be more easily achieved.

In particular, the following new (or changed) interfaces have been introduced:

- `Incoming\Hydrator\Builder`: The basis of the new value instantiation strategy, akin to a hydrator for un-instantiated values/models
- `Incoming\Hydrator\BuilderFactory`: A factory for builders, so that builders can be automatically resolved at runtime, similar to how hydrators work in the current `Processor` logic
- `Incoming\TypeProcessor`: A new interface for enabling the ability to process specific "types", rather than actual model values, allowing you to process with an argument such as `User::class`
- `Incoming\ModelProcessor`: A renaming of the old `ProcessorInterface`, designed to work specifically with already instantiated/constructed models

The `Processor` has been updated to implement both the new `TypeProcessor` **and** the new `ModelProcessor`

This PR also touches on some QoL updates, such as better interface naming and usage of newer PHP 7 features, along with some smaller performance optimizations.

[issue-4-workaround]: https://github.com/Rican7/incoming/issues/4#issuecomment-218520130

### CODE REVIEW

**Comment by Rican7** [comment]
All tests passed! Coverage is still 100%, even with all the new additions. Code quality still 10/10. 👌 

:green_heart: :+1: :shipit:

**Comment by shadowhand** [comment]
Can we get a release with these changes?

**Comment by shadowhand** [comment]
And also an update to the README so that I can better understand how to use the builders?

**Comment by Rican7** [comment]
@shadowhand ... Yes, that's in the works. I'm working on some other parts of the release too, so that the API doesn't have to change multiple times over the 0.x releases.

I'm currently on holiday, though, so please be patient.

**Comment by Rican7** [comment]
@shadowhand Done! [**v0.3.0**](https://github.com/Rican7/incoming/releases/tag/v0.3.0)

**Pull request merged**
